### ISSUE TITLE
setup publishing aka get nuget-ified

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-csharp#12]
I see nuget config, but I suspect we'll need something to set this up for routine publication. I've never done anything like this, so help wanted.

**Comment by abesto** [comment]
Catching up on GitHub notifications. I've never even been near nuget, but I'll keep this on my list in case I run out of Zipkin work and want more. If someone comes around who's more knowledgeable / has motivation: go ahead!

**Comment by aliostad** [comment]
This is fixed now.
