### ISSUE TITLE
I see nuget package install has the dll missing

### ISSUE THREAD

**Issue by prbarl** [openzipkin/zipkin-csharp#13]
I installed the nuget package using visual studio nuget manager. I see only the package file but no zipkin.tracer dll

**Comment by Azert-Mark** [comment]
Hi, yeah I'm also seeing this issue, the nuget package is empty and missing the dlls.

**Comment by aliostad** [comment]
Is this project alive?

**Comment by aliostad** [comment]
Hi guys @prbarl @Azert-Mark 

The project is live again and the nuget is released under **openzipkin**.
You can find it [here](https://www.nuget.org/packages/Zipkin.Core/)

Issues, let me know to open this issue again.

**Comment by prbarl** [comment]
Thank you!
Praveen
