### ISSUE TITLE
Solution must be simply called Zipkin

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin-csharp#19]
Like all other Open Source solutions, the root solution must be simple when encompassing large collection of projects (soon to be big).

~~Also `Tracer`, is not a zipkin concept.~~

**Comment by adriancole** [comment]
Tracer is a type that's used in most zipkin projects, describing the core library used to create instrumentation.

Ex from http://zipkin.io/pages/architecture.html
>Tracers live in your applications and record timing and metadata about operations that took place. They often instrument libraries, so that their use is transparent to users. For example, an instrumented web server records when it received a request and when it sent a response. The trace data collected is called a Span.

Not all tracers repositories are multi-module or cover aspects beyond the tracer. The more code added, the more responsibility on the collaborators, as there's more things to break.

That said, both zipkin-js and brave include both core tracer library and also some highly reused instrumentation
https://github.com/openzipkin/zipkin-js

Intro aside, maybe propose what projects you are expecting to be here?

PS very few people are watching this repo, so they won't see your issue. I'm cc'ing folks who last contributed to discussion on the fate of this repository in #11
cc @jcarres-mdsol @haf @bvillanueva-mdsol @johnberzy-bazinga @lschreck-mdsol

**Comment by adriancole** [comment]
also cc @rogeralsing who opened up other issues here

**Comment by aliostad** [comment]
@adriancole This library is not a tracer. It is the core library implementing core concepts. Hence the naming.

**Comment by adriancole** [comment]
closed via 724ce0e
