### ISSUE TITLE
Possible bug with checkpointing

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin-csharp#30]
Everytime I run the collector, I checkpoint some partitions without adding new spans - possibly pointing to the fact checkpointing is not working.

**Comment by adriancole** [comment]
This would be a great example of an integration test, which should run on
each change possibly with a test account. (something similar is in place
for google stackdriver, although they also made a local mock)

**Comment by aliostad** [comment]
Ah... meant to open against zipkin-azure
